/** Seed catalog with Unsplash image URLs (downloaded locally during seed). */

export const categorySeed = [
  {
    id: "electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Phones, laptops, TVs, audio & gadgets",
    imageUrl:
      "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80",
  },
  {
    id: "fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Clothing, shoes & accessories",
    imageUrl:
      "https://images.unsplash.com/photo-1483986415-9bf75fae7601?w=800&q=80",
  },
  {
    id: "home-kitchen",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Appliances, furniture & decor",
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&q=80",
  },
  {
    id: "beauty",
    name: "Beauty",
    slug: "beauty",
    description: "Skincare, makeup & personal care",
    imageUrl:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80",
  },
  {
    id: "sports",
    name: "Sports & Fitness",
    slug: "sports",
    description: "Gym gear, sportswear & outdoor",
    imageUrl:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
  },
  {
    id: "books",
    name: "Books & Stationery",
    slug: "books",
    description: "Books, notebooks & office supplies",
    imageUrl:
      "https://images.unsplash.com/photo-1512820790801-4153c8c9152f?w=800&q=80",
  },
  {
    id: "toys",
    name: "Toys & Games",
    slug: "toys",
    description: "Kids toys, board games & puzzles",
    imageUrl:
      "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&q=80",
  },
  {
    id: "grocery",
    name: "Groceries & Gourmet",
    slug: "grocery",
    description: "Snacks, beverages & pantry staples",
    imageUrl:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
  },
];

export const bannerSeed = [
  {
    id: "summer-sale",
    imageUrl:
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1400&q=80",
  },
  {
    id: "tech-deals",
    imageUrl:
      "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1400&q=80",
  },
  {
    id: "fashion-week",
    imageUrl:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1400&q=80",
  },
  {
    id: "home-essentials",
    imageUrl:
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1400&q=80",
  },
  {
    id: "beauty-glow",
    imageUrl:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1400&q=80",
  },
  {
    id: "sports-fitness",
    imageUrl:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1400&q=80",
  },
];

export interface ProductSeed {
  name: string;
  slug: string;
  description: string;
  price: number;
  comparePrice?: number;
  category: string;
  brand: string;
  stock: number;
  rating: number;
  reviewCount: number;
  tags: string[];
  specifications: Record<string, string>;
  imageUrl: string;
}

export const productSeed: ProductSeed[] = [
  {
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    description: "Flagship smartphone with 200MP camera and S Pen support.",
    price: 124999,
    comparePrice: 134999,
    category: "Electronics",
    brand: "Samsung",
    stock: 45,
    rating: 4.7,
    reviewCount: 2840,
    tags: ["samsung", "phone", "smartphone", "galaxy", "android", "electronics"],
    specifications: { Display: "6.8\" AMOLED", RAM: "12GB", Storage: "256GB" },
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80",
  },
  {
    name: "Apple iPhone 15",
    slug: "apple-iphone-15",
    description: "Dynamic Island, advanced dual-camera system, USB-C.",
    price: 79900,
    comparePrice: 89900,
    category: "Electronics",
    brand: "Apple",
    stock: 30,
    rating: 4.8,
    reviewCount: 5120,
    tags: ["apple", "iphone", "phone", "ios", "electronics"],
    specifications: { Display: "6.1\" Super Retina", Chip: "A16 Bionic" },
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    slug: "sony-wh-1000xm5",
    description: "Industry-leading noise cancelling wireless headphones.",
    price: 26990,
    comparePrice: 29990,
    category: "Electronics",
    brand: "Sony",
    stock: 80,
    rating: 4.6,
    reviewCount: 1890,
    tags: ["sony", "headphones", "audio", "wireless", "electronics"],
    specifications: { Type: "Over-ear", Connectivity: "Bluetooth 5.3" },
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
  },
  {
    name: "Dell Inspiron 15 Laptop",
    slug: "dell-inspiron-15",
    description: "Everyday laptop with Intel Core i5 and 16GB RAM.",
    price: 54990,
    comparePrice: 62990,
    category: "Electronics",
    brand: "Dell",
    stock: 25,
    rating: 4.3,
    reviewCount: 920,
    tags: ["dell", "laptop", "computer", "electronics"],
    specifications: { Processor: "Intel i5", RAM: "16GB", SSD: "512GB" },
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
  },
  {
    name: "LG 55\" 4K Smart TV",
    slug: "lg-55-4k-tv",
    description: "Ultra HD Smart TV with webOS and HDR10.",
    price: 45999,
    comparePrice: 54999,
    category: "Electronics",
    brand: "LG",
    stock: 15,
    rating: 4.5,
    reviewCount: 654,
    tags: ["lg", "tv", "television", "4k", "electronics"],
    specifications: { Size: "55 inch", Resolution: "4K UHD" },
    imageUrl: "https://images.unsplash.com/photo-1593359673509-e95988baf377?w=800&q=80",
  },
  {
    name: "Boat Airdopes 131",
    slug: "boat-airdopes-131",
    description: "True wireless earbuds with ENx technology.",
    price: 999,
    comparePrice: 2990,
    category: "Electronics",
    brand: "Boat",
    stock: 200,
    rating: 4.2,
    reviewCount: 15200,
    tags: ["boat", "earbuds", "wireless", "audio", "electronics"],
    specifications: { Battery: "42h total", IPX: "IPX4" },
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80",
  },
  {
    name: "OnePlus Nord CE 4",
    slug: "oneplus-nord-ce-4",
    description: "Mid-range phone with 80W fast charging.",
    price: 24999,
    comparePrice: 27999,
    category: "Electronics",
    brand: "OnePlus",
    stock: 60,
    rating: 4.4,
    reviewCount: 1800,
    tags: ["oneplus", "phone", "smartphone", "android", "electronics"],
    specifications: { Display: "6.7\" AMOLED", Charging: "80W" },
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
  },
  {
    name: "HP DeskJet 2330 Printer",
    slug: "hp-deskjet-2330",
    description: "Compact all-in-one printer for home office.",
    price: 3999,
    comparePrice: 5499,
    category: "Electronics",
    brand: "HP",
    stock: 40,
    rating: 4.1,
    reviewCount: 2300,
    tags: ["hp", "printer", "office", "electronics"],
    specifications: { Functions: "Print, Scan, Copy" },
    imageUrl: "https://images.unsplash.com/photo-1612815159322-75f0c48945ba?w=800&q=80",
  },
  {
    name: "Canon EOS R50 Camera",
    slug: "canon-eos-r50",
    description: "Mirrorless camera for creators and vloggers.",
    price: 68999,
    comparePrice: 74999,
    category: "Electronics",
    brand: "Canon",
    stock: 18,
    rating: 4.6,
    reviewCount: 412,
    tags: ["canon", "camera", "photography", "electronics"],
    specifications: { Sensor: "24.2MP APS-C", Video: "4K 30fps" },
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
  },
  {
    name: "Apple Watch Series 9",
    slug: "apple-watch-series-9",
    description: "Advanced health features and bright always-on display.",
    price: 41900,
    comparePrice: 45900,
    category: "Electronics",
    brand: "Apple",
    stock: 55,
    rating: 4.7,
    reviewCount: 2100,
    tags: ["apple", "watch", "wearable", "electronics"],
    specifications: { Size: "45mm", GPS: "Yes" },
    imageUrl: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80",
  },
  {
    name: "Levi's 501 Original Jeans",
    slug: "levis-501-jeans",
    description: "Classic straight fit jeans in durable denim.",
    price: 2999,
    comparePrice: 4499,
    category: "Fashion",
    brand: "Levi's",
    stock: 120,
    rating: 4.4,
    reviewCount: 3200,
    tags: ["levis", "jeans", "denim", "fashion", "mens"],
    specifications: { Fit: "Straight", Material: "100% Cotton" },
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80",
  },
  {
    name: "Nike Air Max 270",
    slug: "nike-air-max-270",
    description: "Lifestyle sneakers with Max Air cushioning.",
    price: 12995,
    comparePrice: 15995,
    category: "Fashion",
    brand: "Nike",
    stock: 65,
    rating: 4.6,
    reviewCount: 2100,
    tags: ["nike", "shoes", "sneakers", "fashion"],
    specifications: { Type: "Lifestyle", Cushioning: "Max Air" },
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
  },
  {
    name: "Allen Solly Formal Shirt",
    slug: "allen-solly-formal-shirt",
    description: "Premium cotton formal shirt for office wear.",
    price: 1499,
    comparePrice: 2499,
    category: "Fashion",
    brand: "Allen Solly",
    stock: 90,
    rating: 4.1,
    reviewCount: 890,
    tags: ["allen solly", "shirt", "formal", "fashion"],
    specifications: { Material: "Cotton", Fit: "Slim" },
    imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b56?w=800&q=80",
  },
  {
    name: "FabIndia Cotton Kurta",
    slug: "fabindia-cotton-kurta",
    description: "Handcrafted ethnic kurta in pure cotton.",
    price: 1899,
    comparePrice: 2799,
    category: "Fashion",
    brand: "FabIndia",
    stock: 55,
    rating: 4.5,
    reviewCount: 420,
    tags: ["fabindia", "kurta", "ethnic", "fashion"],
    specifications: { Material: "Handloom Cotton" },
    imageUrl: "https://images.unsplash.com/photo-1583292650898-7f22f97b2b3b?w=800&q=80",
  },
  {
    name: "Puma Training T-Shirt",
    slug: "puma-training-tshirt",
    description: "Moisture-wicking dryCELL training tee.",
    price: 899,
    comparePrice: 1499,
    category: "Fashion",
    brand: "Puma",
    stock: 150,
    rating: 4.0,
    reviewCount: 1100,
    tags: ["puma", "tshirt", "sports", "fashion"],
    specifications: { Technology: "dryCELL" },
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
  },
  {
    name: "Ray-Ban Aviator Sunglasses",
    slug: "ray-ban-aviator",
    description: "Classic aviator sunglasses with UV protection.",
    price: 8990,
    comparePrice: 10990,
    category: "Fashion",
    brand: "Ray-Ban",
    stock: 40,
    rating: 4.7,
    reviewCount: 780,
    tags: ["rayban", "sunglasses", "fashion", "accessories"],
    specifications: { Lens: "G-15 Green", UV: "100%" },
    imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237ee008?w=800&q=80",
  },
  {
    name: "Zara Linen Blend Blazer",
    slug: "zara-linen-blazer",
    description: "Lightweight blazer for smart casual occasions.",
    price: 5999,
    comparePrice: 7999,
    category: "Fashion",
    brand: "Zara",
    stock: 35,
    rating: 4.3,
    reviewCount: 560,
    tags: ["zara", "blazer", "formal", "fashion"],
    specifications: { Material: "Linen blend", Fit: "Regular" },
    imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80",
  },
  {
    name: "H&M Oversized Hoodie",
    slug: "hm-oversized-hoodie",
    description: "Cozy fleece hoodie for everyday comfort.",
    price: 1999,
    comparePrice: 2999,
    category: "Fashion",
    brand: "H&M",
    stock: 110,
    rating: 4.2,
    reviewCount: 1450,
    tags: ["hm", "hoodie", "casual", "fashion"],
    specifications: { Material: "Cotton blend" },
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80",
  },
  {
    name: "Prestige Iris 750W Mixer Grinder",
    slug: "prestige-mixer-grinder",
    description: "3-jar mixer grinder with stainless steel blades.",
    price: 3299,
    comparePrice: 4299,
    category: "Home & Kitchen",
    brand: "Prestige",
    stock: 70,
    rating: 4.3,
    reviewCount: 4500,
    tags: ["prestige", "mixer", "kitchen", "appliance"],
    specifications: { Power: "750W", Jars: "3" },
    imageUrl: "https://images.unsplash.com/photo-1570223605840-4a118d396a3f?w=800&q=80",
  },
  {
    name: "Milton Thermosteel Flask 1L",
    slug: "milton-thermosteel-flask",
    description: "Vacuum insulated flask — hot/cold for 24 hours.",
    price: 649,
    comparePrice: 999,
    category: "Home & Kitchen",
    brand: "Milton",
    stock: 300,
    rating: 4.4,
    reviewCount: 8900,
    tags: ["milton", "flask", "kitchen", "thermos"],
    specifications: { Capacity: "1 Litre" },
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
  },
  {
    name: "Philips Air Fryer HD9200",
    slug: "philips-air-fryer",
    description: "Healthy frying with Rapid Air, 4.1L capacity.",
    price: 8999,
    comparePrice: 11995,
    category: "Home & Kitchen",
    brand: "Philips",
    stock: 35,
    rating: 4.5,
    reviewCount: 2100,
    tags: ["philips", "airfryer", "kitchen", "appliance"],
    specifications: { Capacity: "4.1L", Power: "1400W" },
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80",
  },
  {
    name: "Wakefit Orthopedic Mattress",
    slug: "wakefit-mattress",
    description: "Medium firm memory foam mattress.",
    price: 8999,
    comparePrice: 14999,
    category: "Home & Kitchen",
    brand: "Wakefit",
    stock: 20,
    rating: 4.6,
    reviewCount: 5600,
    tags: ["wakefit", "mattress", "bedroom", "furniture"],
    specifications: { Size: "Queen", Thickness: "6 inch" },
    imageUrl: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
  },
  {
    name: "Cello Opalware Dinner Set 27pcs",
    slug: "cello-dinner-set",
    description: "Elegant opalware dinner set for 6.",
    price: 1599,
    comparePrice: 2499,
    category: "Home & Kitchen",
    brand: "Cello",
    stock: 85,
    rating: 4.2,
    reviewCount: 3400,
    tags: ["cello", "dinner", "kitchen", "opalware"],
    specifications: { Pieces: "27" },
    imageUrl: "https://images.unsplash.com/photo-1603199506016-b9a594bfbe43?w=800&q=80",
  },
  {
    name: "IKEA MALM Bed Frame",
    slug: "ikea-malm-bed",
    description: "Minimal queen bed frame with storage drawers.",
    price: 18999,
    comparePrice: 22999,
    category: "Home & Kitchen",
    brand: "IKEA",
    stock: 12,
    rating: 4.4,
    reviewCount: 890,
    tags: ["ikea", "bed", "furniture", "bedroom"],
    specifications: { Size: "Queen", Material: "Particle board" },
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
  },
  {
    name: "Dyson V12 Detect Vacuum",
    slug: "dyson-v12-vacuum",
    description: "Cordless vacuum with laser dust detection.",
    price: 52900,
    comparePrice: 59900,
    category: "Home & Kitchen",
    brand: "Dyson",
    stock: 22,
    rating: 4.8,
    reviewCount: 1200,
    tags: ["dyson", "vacuum", "cleaning", "appliance"],
    specifications: { Runtime: "60 min", Weight: "2.2 kg" },
    imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30012?w=800&q=80",
  },
  {
    name: "L'Oreal Paris Revitalift Serum",
    slug: "loreal-revitalift-serum",
    description: "Anti-aging serum with hyaluronic acid.",
    price: 899,
    comparePrice: 1299,
    category: "Beauty",
    brand: "L'Oreal",
    stock: 180,
    rating: 4.3,
    reviewCount: 6700,
    tags: ["loreal", "serum", "skincare", "beauty"],
    specifications: { Volume: "30ml", Type: "Serum" },
    imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80",
  },
  {
    name: "Maybelline Fit Me Foundation",
    slug: "maybelline-fit-me",
    description: "Natural matte foundation for all skin types.",
    price: 549,
    comparePrice: 699,
    category: "Beauty",
    brand: "Maybelline",
    stock: 250,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["maybelline", "foundation", "makeup", "beauty"],
    specifications: { Finish: "Matte", SPF: "15" },
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80",
  },
  {
    name: "The Ordinary Niacinamide 10%",
    slug: "ordinary-niacinamide",
    description: "Blemish and pore refining serum.",
    price: 650,
    comparePrice: 800,
    category: "Beauty",
    brand: "The Ordinary",
    stock: 140,
    rating: 4.6,
    reviewCount: 4200,
    tags: ["ordinary", "niacinamide", "skincare", "beauty"],
    specifications: { Volume: "30ml" },
    imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80",
  },
  {
    name: "Philips Sonicare Toothbrush",
    slug: "philips-sonicare",
    description: "Electric toothbrush with 3 cleaning modes.",
    price: 3999,
    comparePrice: 4999,
    category: "Beauty",
    brand: "Philips",
    stock: 75,
    rating: 4.5,
    reviewCount: 3100,
    tags: ["philips", "toothbrush", "oral care", "beauty"],
    specifications: { Modes: "3", Battery: "2 weeks" },
    imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800&q=80",
  },
  {
    name: "Biotique Bio Kelp Shampoo",
    slug: "biotique-kelp-shampoo",
    description: "Ayurvedic protein shampoo for hair fall control.",
    price: 199,
    comparePrice: 275,
    category: "Beauty",
    brand: "Biotique",
    stock: 400,
    rating: 4.1,
    reviewCount: 11200,
    tags: ["biotique", "shampoo", "hair care", "beauty"],
    specifications: { Volume: "340ml" },
    imageUrl: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80",
  },
  {
    name: "Yoga Mat Pro 6mm",
    slug: "yoga-mat-pro",
    description: "Non-slip exercise mat with carrying strap.",
    price: 1299,
    comparePrice: 1999,
    category: "Sports & Fitness",
    brand: "Strauss",
    stock: 160,
    rating: 4.4,
    reviewCount: 2800,
    tags: ["yoga", "mat", "fitness", "sports"],
    specifications: { Thickness: "6mm", Material: "TPE" },
    imageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80",
  },
  {
    name: "Adjustable Dumbbell Set 20kg",
    slug: "dumbbell-set-20kg",
    description: "Home gym dumbbells with quick-lock plates.",
    price: 4999,
    comparePrice: 6999,
    category: "Sports & Fitness",
    brand: "Boldfit",
    stock: 45,
    rating: 4.3,
    reviewCount: 1560,
    tags: ["dumbbell", "gym", "fitness", "sports"],
    specifications: { Weight: "20kg pair" },
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fcb2f61b?w=800&q=80",
  },
  {
    name: "Nivia Football Size 5",
    slug: "nivia-football",
    description: "FIFA-approved match football with superior grip.",
    price: 899,
    comparePrice: 1299,
    category: "Sports & Fitness",
    brand: "Nivia",
    stock: 200,
    rating: 4.2,
    reviewCount: 3400,
    tags: ["nivia", "football", "sports", "outdoor"],
    specifications: { Size: "5", Material: "PU" },
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
  },
  {
    name: "Garmin Forerunner 255",
    slug: "garmin-forerunner-255",
    description: "GPS running watch with advanced training metrics.",
    price: 37999,
    comparePrice: 42999,
    category: "Sports & Fitness",
    brand: "Garmin",
    stock: 28,
    rating: 4.7,
    reviewCount: 890,
    tags: ["garmin", "watch", "running", "sports", "fitness"],
    specifications: { GPS: "Multi-band", Battery: "14 days" },
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
  },
  {
    name: "Atomic Habits — James Clear",
    slug: "atomic-habits-book",
    description: "Bestselling guide to building good habits.",
    price: 399,
    comparePrice: 599,
    category: "Books & Stationery",
    brand: "Penguin",
    stock: 500,
    rating: 4.9,
    reviewCount: 45000,
    tags: ["book", "self help", "atomic habits", "books"],
    specifications: { Pages: "320", Language: "English" },
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
  },
  {
    name: "Classmate Notebook Pack of 6",
    slug: "classmate-notebook-pack",
    description: "Long-size ruled notebooks, 180 pages each.",
    price: 299,
    comparePrice: 420,
    category: "Books & Stationery",
    brand: "Classmate",
    stock: 600,
    rating: 4.5,
    reviewCount: 8900,
    tags: ["classmate", "notebook", "stationery", "books"],
    specifications: { Pages: "180", Pack: "6" },
    imageUrl: "https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=800&q=80",
  },
  {
    name: "Parker Jotter Ballpoint Pen",
    slug: "parker-jotter-pen",
    description: "Iconic stainless steel ballpoint pen.",
    price: 450,
    comparePrice: 550,
    category: "Books & Stationery",
    brand: "Parker",
    stock: 320,
    rating: 4.6,
    reviewCount: 5600,
    tags: ["parker", "pen", "stationery", "office"],
    specifications: { Ink: "Blue", Material: "Steel" },
    imageUrl: "https://images.unsplash.com/photo-1585366111167-4414a7fdb77b?w=800&q=80",
  },
  {
    name: "The Psychology of Money",
    slug: "psychology-of-money",
    description: "Timeless lessons on wealth and happiness.",
    price: 350,
    comparePrice: 499,
    category: "Books & Stationery",
    brand: "Jaico",
    stock: 280,
    rating: 4.8,
    reviewCount: 22000,
    tags: ["book", "finance", "money", "books"],
    specifications: { Pages: "256" },
    imageUrl: "https://images.unsplash.com/photo-1512820790801-4153c8c9152f?w=800&q=80",
  },
  {
    name: "LEGO Classic Creative Bricks",
    slug: "lego-classic-bricks",
    description: "790-piece LEGO set for creative building fun.",
    price: 3499,
    comparePrice: 4299,
    category: "Toys & Games",
    brand: "LEGO",
    stock: 85,
    rating: 4.8,
    reviewCount: 6200,
    tags: ["lego", "toys", "building", "kids"],
    specifications: { Pieces: "790", Age: "4+" },
    imageUrl: "https://images.unsplash.com/photo-1587654780291-39fd940a746b?w=800&q=80",
  },
  {
    name: "Hot Wheels Track Builder Set",
    slug: "hot-wheels-track-set",
    description: "Stunt track with loops and launchers for die-cast cars.",
    price: 1999,
    comparePrice: 2799,
    category: "Toys & Games",
    brand: "Hot Wheels",
    stock: 120,
    rating: 4.5,
    reviewCount: 3400,
    tags: ["hot wheels", "cars", "toys", "track"],
    specifications: { Cars: "2 included", Age: "5+" },
    imageUrl: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&q=80",
  },
  {
    name: "Monopoly Classic Board Game",
    slug: "monopoly-classic",
    description: "The world's favourite property trading board game.",
    price: 1299,
    comparePrice: 1599,
    category: "Toys & Games",
    brand: "Hasbro",
    stock: 200,
    rating: 4.6,
    reviewCount: 8900,
    tags: ["monopoly", "board game", "hasbro", "toys"],
    specifications: { Players: "2-6", Age: "8+" },
    imageUrl: "https://images.unsplash.com/photo-1611195974226-ef8750c8b5c0?w=800&q=80",
  },
  {
    name: "Barbie Dreamhouse Playset",
    slug: "barbie-dreamhouse",
    description: "Three-story dollhouse with elevator and pool.",
    price: 8999,
    comparePrice: 11999,
    category: "Toys & Games",
    brand: "Barbie",
    stock: 35,
    rating: 4.7,
    reviewCount: 2100,
    tags: ["barbie", "dollhouse", "toys", "kids"],
    specifications: { Height: "109cm", Age: "3+" },
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e17ddd77?w=800&q=80",
  },
  {
    name: "Organic Honey 500g",
    slug: "organic-honey-500g",
    description: "Pure wild forest honey, unprocessed and raw.",
    price: 399,
    comparePrice: 499,
    category: "Groceries & Gourmet",
    brand: "Dabur",
    stock: 350,
    rating: 4.4,
    reviewCount: 5600,
    tags: ["honey", "organic", "grocery", "dabur"],
    specifications: { Weight: "500g", Type: "Wild Forest" },
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
  },
  {
    name: "Tata Tea Premium 1kg",
    slug: "tata-tea-premium",
    description: "Strong and refreshing blend of Assam tea leaves.",
    price: 520,
    comparePrice: 580,
    category: "Groceries & Gourmet",
    brand: "Tata",
    stock: 500,
    rating: 4.3,
    reviewCount: 12400,
    tags: ["tea", "tata", "grocery", "beverages"],
    specifications: { Weight: "1kg", Origin: "Assam" },
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9fcdd?w=800&q=80",
  },
  {
    name: "Kellogg's Corn Flakes 875g",
    slug: "kelloggs-corn-flakes",
    description: "Crispy golden flakes — a classic breakfast cereal.",
    price: 299,
    comparePrice: 350,
    category: "Groceries & Gourmet",
    brand: "Kellogg's",
    stock: 420,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["cereal", "breakfast", "kelloggs", "grocery"],
    specifications: { Weight: "875g" },
    imageUrl: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800&q=80",
  },
  {
    name: "Amul Dark Chocolate 150g",
    slug: "amul-dark-chocolate",
    description: "Rich 55% cocoa dark chocolate bar.",
    price: 175,
    comparePrice: 200,
    category: "Groceries & Gourmet",
    brand: "Amul",
    stock: 600,
    rating: 4.5,
    reviewCount: 7200,
    tags: ["chocolate", "amul", "snacks", "grocery"],
    specifications: { Weight: "150g", Cocoa: "55%" },
    imageUrl: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800&q=80",
  },
  {
    name: "Bose QuietComfort Ultra",
    slug: "bose-qc-ultra",
    description: "Premium noise-cancelling headphones with spatial audio.",
    price: 34900,
    comparePrice: 38900,
    category: "Electronics",
    brand: "Bose",
    stock: 22,
    rating: 4.8,
    reviewCount: 1240,
    tags: ["bose", "headphones", "audio", "electronics"],
    specifications: { ANC: "Yes", Battery: "24h" },
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
  },
  {
    name: "Canon EOS R50 Mirrorless",
    slug: "canon-eos-r50",
    description: "Compact APS-C mirrorless camera with 4K video.",
    price: 68995,
    comparePrice: 74995,
    category: "Electronics",
    brand: "Canon",
    stock: 18,
    rating: 4.7,
    reviewCount: 890,
    tags: ["canon", "camera", "photography", "electronics"],
    specifications: { Sensor: "APS-C", Video: "4K 30fps" },
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
  },
  {
    name: "Levi's 501 Original Jeans",
    slug: "levis-501-jeans",
    description: "Iconic straight-fit denim jeans with button fly.",
    price: 3999,
    comparePrice: 4999,
    category: "Fashion",
    brand: "Levi's",
    stock: 180,
    rating: 4.5,
    reviewCount: 8900,
    tags: ["levis", "jeans", "denim", "fashion"],
    specifications: { Fit: "Straight", Material: "Cotton" },
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80",
  },
  {
    name: "Ray-Ban Aviator Classic",
    slug: "rayban-aviator",
    description: "Timeless aviator sunglasses with G-15 lenses.",
    price: 8990,
    comparePrice: 10990,
    category: "Fashion",
    brand: "Ray-Ban",
    stock: 65,
    rating: 4.6,
    reviewCount: 4200,
    tags: ["rayban", "sunglasses", "fashion", "accessories"],
    specifications: { Lens: "G-15 Green", Frame: "Metal" },
    imageUrl: "https://images.unsplash.com/photo-1572635196233-224f5e298d8a?w=800&q=80",
  },
  {
    name: "Dyson V15 Detect Vacuum",
    slug: "dyson-v15-detect",
    description: "Laser-detect cordless vacuum with HEPA filtration.",
    price: 62900,
    comparePrice: 69900,
    category: "Home & Kitchen",
    brand: "Dyson",
    stock: 25,
    rating: 4.8,
    reviewCount: 1560,
    tags: ["dyson", "vacuum", "home", "cleaning"],
    specifications: { Runtime: "60 min", Weight: "3.1 kg" },
    imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30029?w=800&q=80",
  },
  {
    name: "Nike Air Max 270",
    slug: "nike-air-max-270",
    description: "Lifestyle sneakers with Max Air heel unit.",
    price: 12995,
    comparePrice: 14995,
    category: "Sports & Fitness",
    brand: "Nike",
    stock: 95,
    rating: 4.5,
    reviewCount: 6700,
    tags: ["nike", "shoes", "sneakers", "sports"],
    specifications: { Type: "Lifestyle", Cushion: "Max Air" },
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
  },
  {
    name: "Sapiens — Yuval Noah Harari",
    slug: "sapiens-book",
    description: "A brief history of humankind — international bestseller.",
    price: 450,
    comparePrice: 599,
    category: "Books & Stationery",
    brand: "Penguin",
    stock: 380,
    rating: 4.9,
    reviewCount: 52000,
    tags: ["book", "sapiens", "history", "books"],
    specifications: { Pages: "512", Language: "English" },
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
  },
];
