import type { OrderStatus } from "../types";

export const SEED_CUSTOMER_PASSWORD = "Customer@123456";

export interface CustomerSeed {
  email: string;
  displayName: string;
  phone: string;
  city: string;
  state: string;
  pincode: string;
}

export const customerSeed: CustomerSeed[] = [
  {
    email: "priya.sharma@example.com",
    displayName: "Priya Sharma",
    phone: "9876543210",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
  },
  {
    email: "rahul.verma@example.com",
    displayName: "Rahul Verma",
    phone: "9876543211",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
  },
  {
    email: "ananya.patel@example.com",
    displayName: "Ananya Patel",
    phone: "9876543212",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380001",
  },
  {
    email: "vikram.singh@example.com",
    displayName: "Vikram Singh",
    phone: "9876543213",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
  },
  {
    email: "meera.iyer@example.com",
    displayName: "Meera Iyer",
    phone: "9876543214",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560001",
  },
  {
    email: "arjun.nair@example.com",
    displayName: "Arjun Nair",
    phone: "9876543215",
    city: "Kochi",
    state: "Kerala",
    pincode: "682001",
  },
  {
    email: "kavya.reddy@example.com",
    displayName: "Kavya Reddy",
    phone: "9876543216",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500001",
  },
  {
    email: "rohan.malhotra@example.com",
    displayName: "Rohan Malhotra",
    phone: "9876543217",
    city: "Chandigarh",
    state: "Punjab",
    pincode: "160001",
  },
  {
    email: "divya.gupta@example.com",
    displayName: "Divya Gupta",
    phone: "9876543218",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
  },
  {
    email: "suresh.kumar@example.com",
    displayName: "Suresh Kumar",
    phone: "9876543219",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600001",
  },
  {
    email: "neha.desai@example.com",
    displayName: "Neha Desai",
    phone: "9876543220",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001",
  },
  {
    email: "amit.joshi@example.com",
    displayName: "Amit Joshi",
    phone: "9876543221",
    city: "Indore",
    state: "Madhya Pradesh",
    pincode: "452001",
  },
];

export interface OrderItemSeed {
  productSlug: string;
  quantity: number;
}

export interface OrderSeed {
  customerIndex: number;
  items: OrderItemSeed[];
  status: OrderStatus;
  daysAgo: number;
  trackingNumber?: string;
}

export const orderSeed: OrderSeed[] = [
  {
    customerIndex: 0,
    items: [{ productSlug: "samsung-galaxy-s24-ultra", quantity: 1 }],
    status: "delivered",
    daysAgo: 28,
    trackingNumber: "NC8945210IN",
  },
  {
    customerIndex: 0,
    items: [
      { productSlug: "apple-iphone-15", quantity: 1 },
      { productSlug: "bose-qc-ultra", quantity: 1 },
    ],
    status: "shipped",
    daysAgo: 5,
    trackingNumber: "NC9012345IN",
  },
  {
    customerIndex: 1,
    items: [{ productSlug: "nike-air-max-270", quantity: 1 }],
    status: "delivered",
    daysAgo: 22,
    trackingNumber: "NC8822100IN",
  },
  {
    customerIndex: 1,
    items: [{ productSlug: "levis-501-jeans", quantity: 2 }],
    status: "processing",
    daysAgo: 3,
  },
  {
    customerIndex: 2,
    items: [{ productSlug: "dyson-v15-detect", quantity: 1 }],
    status: "delivered",
    daysAgo: 18,
    trackingNumber: "NC8755001IN",
  },
  {
    customerIndex: 2,
    items: [
      { productSlug: "philips-air-fryer", quantity: 1 },
      { productSlug: "cello-dinner-set", quantity: 1 },
    ],
    status: "confirmed",
    daysAgo: 2,
  },
  {
    customerIndex: 3,
    items: [{ productSlug: "garmin-forerunner-255", quantity: 1 }],
    status: "delivered",
    daysAgo: 15,
    trackingNumber: "NC8600123IN",
  },
  {
    customerIndex: 3,
    items: [{ productSlug: "yoga-mat-pro", quantity: 1 }],
    status: "cancelled",
    daysAgo: 10,
  },
  {
    customerIndex: 4,
    items: [
      { productSlug: "loreal-revitalift-serum", quantity: 2 },
      { productSlug: "maybelline-fit-me", quantity: 1 },
    ],
    status: "delivered",
    daysAgo: 12,
    trackingNumber: "NC8512345IN",
  },
  {
    customerIndex: 4,
    items: [{ productSlug: "rayban-aviator", quantity: 1 }],
    status: "shipped",
    daysAgo: 4,
    trackingNumber: "NC9099887IN",
  },
  {
    customerIndex: 5,
    items: [{ productSlug: "canon-eos-r50", quantity: 1 }],
    status: "processing",
    daysAgo: 6,
  },
  {
    customerIndex: 5,
    items: [{ productSlug: "sony-wh-1000xm5", quantity: 1 }],
    status: "delivered",
    daysAgo: 25,
    trackingNumber: "NC8400001IN",
  },
  {
    customerIndex: 6,
    items: [
      { productSlug: "atomic-habits-book", quantity: 1 },
      { productSlug: "sapiens-book", quantity: 1 },
    ],
    status: "delivered",
    daysAgo: 8,
    trackingNumber: "NC8777123IN",
  },
  {
    customerIndex: 6,
    items: [{ productSlug: "classmate-notebook-pack", quantity: 3 }],
    status: "confirmed",
    daysAgo: 1,
  },
  {
    customerIndex: 7,
    items: [{ productSlug: "lego-classic-bricks", quantity: 1 }],
    status: "delivered",
    daysAgo: 20,
    trackingNumber: "NC8654321IN",
  },
  {
    customerIndex: 7,
    items: [{ productSlug: "hot-wheels-track-set", quantity: 2 }],
    status: "pending",
    daysAgo: 0,
  },
  {
    customerIndex: 8,
    items: [
      { productSlug: "organic-honey-500g", quantity: 2 },
      { productSlug: "tata-tea-premium", quantity: 1 },
    ],
    status: "delivered",
    daysAgo: 14,
    trackingNumber: "NC8543210IN",
  },
  {
    customerIndex: 8,
    items: [{ productSlug: "amul-dark-chocolate", quantity: 4 }],
    status: "shipped",
    daysAgo: 7,
    trackingNumber: "NC8987654IN",
  },
  {
    customerIndex: 9,
    items: [{ productSlug: "dell-inspiron-15", quantity: 1 }],
    status: "delivered",
    daysAgo: 30,
    trackingNumber: "NC8300001IN",
  },
  {
    customerIndex: 9,
    items: [{ productSlug: "lg-55-4k-tv", quantity: 1 }],
    status: "processing",
    daysAgo: 9,
  },
  {
    customerIndex: 10,
    items: [
      { productSlug: "puma-training-tshirt", quantity: 1 },
      { productSlug: "nivia-football", quantity: 1 },
    ],
    status: "delivered",
    daysAgo: 16,
    trackingNumber: "NC8622100IN",
  },
  {
    customerIndex: 10,
    items: [{ productSlug: "dumbbell-set-20kg", quantity: 1 }],
    status: "confirmed",
    daysAgo: 2,
  },
  {
    customerIndex: 11,
    items: [{ productSlug: "oneplus-nord-ce-4", quantity: 1 }],
    status: "delivered",
    daysAgo: 11,
    trackingNumber: "NC8711000IN",
  },
  {
    customerIndex: 11,
    items: [
      { productSlug: "boat-airdopes-131", quantity: 1 },
      { productSlug: "kelloggs-corn-flakes", quantity: 2 },
    ],
    status: "shipped",
    daysAgo: 3,
    trackingNumber: "NC9055000IN",
  },
  {
    customerIndex: 0,
    items: [{ productSlug: "psychology-of-money", quantity: 1 }],
    status: "delivered",
    daysAgo: 6,
    trackingNumber: "NC9123000IN",
  },
  {
    customerIndex: 3,
    items: [{ productSlug: "barbie-dreamhouse", quantity: 1 }],
    status: "processing",
    daysAgo: 4,
  },
  {
    customerIndex: 5,
    items: [{ productSlug: "monopoly-classic", quantity: 1 }],
    status: "delivered",
    daysAgo: 9,
    trackingNumber: "NC8899001IN",
  },
  {
    customerIndex: 2,
    items: [{ productSlug: "wakefit-mattress", quantity: 1 }],
    status: "delivered",
    daysAgo: 27,
    trackingNumber: "NC8200100IN",
  },
  {
    customerIndex: 4,
    items: [{ productSlug: "philips-sonicare", quantity: 1 }],
    status: "cancelled",
    daysAgo: 13,
  },
  {
    customerIndex: 6,
    items: [{ productSlug: "parker-jotter-pen", quantity: 2 }],
    status: "delivered",
    daysAgo: 19,
    trackingNumber: "NC8567890IN",
  },
  {
    customerIndex: 8,
    items: [{ productSlug: "ikea-malm-bed", quantity: 1 }],
    status: "shipped",
    daysAgo: 5,
    trackingNumber: "NC9032100IN",
  },
];

export interface ReviewSeed {
  customerIndex: number;
  productSlug: string;
  rating: number;
  title: string;
  body: string;
  verified: boolean;
  daysAgo: number;
}

export const reviewSeed: ReviewSeed[] = [
  {
    customerIndex: 0,
    productSlug: "samsung-galaxy-s24-ultra",
    rating: 5,
    title: "Best flagship phone",
    body: "Camera is incredible and battery easily lasts a full day. S Pen is a bonus for notes.",
    verified: true,
    daysAgo: 26,
  },
  {
    customerIndex: 0,
    productSlug: "apple-iphone-15",
    rating: 4,
    title: "Smooth and premium",
    body: "Great performance and display. Wish it had a higher refresh rate.",
    verified: true,
    daysAgo: 4,
  },
  {
    customerIndex: 1,
    productSlug: "nike-air-max-270",
    rating: 5,
    title: "Super comfortable",
    body: "Wore them all day on a trip — no foot fatigue. True to size.",
    verified: true,
    daysAgo: 20,
  },
  {
    customerIndex: 1,
    productSlug: "levis-501-jeans",
    rating: 4,
    title: "Classic fit",
    body: "Good quality denim. Took a day to break in but fits perfectly now.",
    verified: false,
    daysAgo: 2,
  },
  {
    customerIndex: 2,
    productSlug: "dyson-v15-detect",
    rating: 5,
    title: "Worth every rupee",
    body: "Laser dust detection is no gimmick — floors have never been cleaner.",
    verified: true,
    daysAgo: 16,
  },
  {
    customerIndex: 2,
    productSlug: "philips-air-fryer",
    rating: 4,
    title: "Healthy frying made easy",
    body: "Crispy fries with less oil. Basket is a bit small for a family of four.",
    verified: true,
    daysAgo: 1,
  },
  {
    customerIndex: 3,
    productSlug: "garmin-forerunner-255",
    rating: 5,
    title: "Runner's dream watch",
    body: "GPS locks fast and training metrics are spot on. Battery lasts two weeks.",
    verified: true,
    daysAgo: 13,
  },
  {
    customerIndex: 4,
    productSlug: "loreal-revitalift-serum",
    rating: 4,
    title: "Visible glow in 2 weeks",
    body: "Skin feels firmer. Lightweight formula absorbs quickly.",
    verified: true,
    daysAgo: 10,
  },
  {
    customerIndex: 4,
    productSlug: "rayban-aviator",
    rating: 5,
    title: "Timeless style",
    body: "Authentic Ray-Ban quality. Polarised lenses would be nice at this price.",
    verified: true,
    daysAgo: 3,
  },
  {
    customerIndex: 5,
    productSlug: "sony-wh-1000xm5",
    rating: 5,
    title: "ANC king",
    body: "Blocks out metro noise completely. Comfort is excellent for long flights.",
    verified: true,
    daysAgo: 23,
  },
  {
    customerIndex: 5,
    productSlug: "canon-eos-r50",
    rating: 4,
    title: "Great starter mirrorless",
    body: "Compact and easy to use. Kit lens is fine; upgraded to a prime later.",
    verified: false,
    daysAgo: 5,
  },
  {
    customerIndex: 6,
    productSlug: "atomic-habits-book",
    rating: 5,
    title: "Life-changing read",
    body: "Practical advice on building habits. Already recommended to three friends.",
    verified: true,
    daysAgo: 7,
  },
  {
    customerIndex: 6,
    productSlug: "sapiens-book",
    rating: 5,
    title: "Mind-blowing history",
    body: "Harari makes complex ideas accessible. Could not put it down.",
    verified: true,
    daysAgo: 6,
  },
  {
    customerIndex: 7,
    productSlug: "lego-classic-bricks",
    rating: 5,
    title: "Kids love it",
    body: "Hours of creative play. Pieces are sturdy and colours are vibrant.",
    verified: true,
    daysAgo: 18,
  },
  {
    customerIndex: 7,
    productSlug: "hot-wheels-track-set",
    rating: 4,
    title: "Fun stunt track",
    body: "Loops work well on a flat floor. Some assembly needed — took 20 minutes.",
    verified: false,
    daysAgo: 0,
  },
  {
    customerIndex: 8,
    productSlug: "organic-honey-500g",
    rating: 4,
    title: "Pure and tasty",
    body: "Thick consistency and natural sweetness. Good for morning tea.",
    verified: true,
    daysAgo: 12,
  },
  {
    customerIndex: 8,
    productSlug: "amul-dark-chocolate",
    rating: 5,
    title: "Rich cocoa flavour",
    body: "Not too sweet — perfect dark chocolate. Stock up during sales.",
    verified: true,
    daysAgo: 6,
  },
  {
    customerIndex: 9,
    productSlug: "dell-inspiron-15",
    rating: 5,
    title: "Blazing fast laptop",
    body: "Silent, light, and handles video editing without breaking a sweat.",
    verified: true,
    daysAgo: 28,
  },
  {
    customerIndex: 10,
    productSlug: "puma-training-tshirt",
    rating: 4,
    title: "Good for daily runs",
    body: "Cushioning is solid for 5K runs. Sizing runs slightly narrow.",
    verified: true,
    daysAgo: 14,
  },
  {
    customerIndex: 10,
    productSlug: "dumbbell-set-20kg",
    rating: 4,
    title: "Home gym essential",
    body: "Quick plate changes. A stand would make it even better.",
    verified: false,
    daysAgo: 1,
  },
  {
    customerIndex: 11,
    productSlug: "oneplus-nord-ce-4",
    rating: 5,
    title: "Flagship killer",
    body: "Charging speed is insane. Display is bright even in sunlight.",
    verified: true,
    daysAgo: 9,
  },
  {
    customerIndex: 11,
    productSlug: "boat-airdopes-131",
    rating: 4,
    title: "Great value fitness band",
    body: "Sleep tracking is accurate. App could be more polished.",
    verified: true,
    daysAgo: 2,
  },
  {
    customerIndex: 0,
    productSlug: "bose-qc-ultra",
    rating: 5,
    title: "Premium sound",
    body: "Spatial audio is immersive. Best headphones I have owned.",
    verified: true,
    daysAgo: 3,
  },
  {
    customerIndex: 3,
    productSlug: "nivia-football",
    rating: 4,
    title: "Good match ball",
    body: "Grip is excellent on grass. Holds air well after weeks of use.",
    verified: true,
    daysAgo: 8,
  },
  {
    customerIndex: 2,
    productSlug: "wakefit-mattress",
    rating: 5,
    title: "Back pain gone",
    body: "Firm support without feeling hard. Delivery and setup were smooth.",
    verified: true,
    daysAgo: 25,
  },
  {
    customerIndex: 4,
    productSlug: "maybelline-fit-me",
    rating: 4,
    title: "Natural matte finish",
    body: "Blends easily and stays put for 8+ hours. Good shade range.",
    verified: true,
    daysAgo: 11,
  },
  {
    customerIndex: 6,
    productSlug: "classmate-notebook-pack",
    rating: 5,
    title: "Student staple",
    body: "Smooth pages and sturdy binding. Great value for a 6-pack.",
    verified: true,
    daysAgo: 5,
  },
  {
    customerIndex: 8,
    productSlug: "tata-tea-premium",
    rating: 4,
    title: "Strong morning chai",
    body: "Bold flavour — one teaspoon is enough per cup.",
    verified: true,
    daysAgo: 13,
  },
  {
    customerIndex: 9,
    productSlug: "lg-55-4k-tv",
    rating: 5,
    title: "Stunning picture",
    body: "Colours pop on 4K content. Smart TV apps load quickly.",
    verified: false,
    daysAgo: 7,
  },
  {
    customerIndex: 1,
    productSlug: "samsung-galaxy-s24-ultra",
    rating: 4,
    title: "Almost perfect",
    body: "Slightly heavy but the camera zoom is unmatched.",
    verified: false,
    daysAgo: 15,
  },
  {
    customerIndex: 5,
    productSlug: "monopoly-classic",
    rating: 5,
    title: "Family game night",
    body: "Classic board game — kids and adults enjoyed it equally.",
    verified: true,
    daysAgo: 8,
  },
  {
    customerIndex: 7,
    productSlug: "barbie-dreamhouse",
    rating: 5,
    title: "Dream gift",
    body: "Huge playset with lots of accessories. Assembly took an hour.",
    verified: true,
    daysAgo: 3,
  },
  {
    customerIndex: 10,
    productSlug: "nivia-football",
    rating: 3,
    title: "Decent for practice",
    body: "Fine for casual kickabouts. Pro players may want something softer.",
    verified: false,
    daysAgo: 4,
  },
  {
    customerIndex: 3,
    productSlug: "yoga-mat-pro",
    rating: 4,
    title: "Non-slip surface",
    body: "Good grip during hot yoga. Carrying strap is handy.",
    verified: false,
    daysAgo: 9,
  },
  {
    customerIndex: 8,
    productSlug: "kelloggs-corn-flakes",
    rating: 4,
    title: "Crunchy breakfast",
    body: "Fresh and crispy. Kids finish the box in a week.",
    verified: true,
    daysAgo: 2,
  },
  {
    customerIndex: 11,
    productSlug: "psychology-of-money",
    rating: 5,
    title: "Must-read finance book",
    body: "Short chapters with powerful lessons on wealth and behaviour.",
    verified: true,
    daysAgo: 10,
  },
  {
    customerIndex: 4,
    productSlug: "biotique-kelp-shampoo",
    rating: 3,
    title: "Okay for the price",
    body: "Mild herbal scent. Did not see major hair-fall reduction yet.",
    verified: false,
    daysAgo: 14,
  },
  {
    customerIndex: 0,
    productSlug: "psychology-of-money",
    rating: 5,
    title: "Highly recommend",
    body: "Changed how I think about saving and investing.",
    verified: true,
    daysAgo: 5,
  },
];

/** customerIndex -> product slugs for wishlist subcollection */
export const wishlistSeed: { customerIndex: number; productSlugs: string[] }[] = [
  {
    customerIndex: 0,
    productSlugs: ["dell-inspiron-15", "rayban-aviator", "canon-eos-r50"],
  },
  {
    customerIndex: 1,
    productSlugs: ["nike-air-max-270", "garmin-forerunner-255", "bose-qc-ultra"],
  },
  {
    customerIndex: 2,
    productSlugs: ["dyson-v15-detect", "ikea-malm-bed", "lg-55-4k-tv"],
  },
  {
    customerIndex: 4,
    productSlugs: [
      "loreal-revitalift-serum",
      "maybelline-fit-me",
      "ordinary-niacinamide",
    ],
  },
  {
    customerIndex: 5,
    productSlugs: ["sony-wh-1000xm5", "oneplus-nord-ce-4", "samsung-galaxy-s24-ultra"],
  },
  {
    customerIndex: 6,
    productSlugs: ["atomic-habits-book", "sapiens-book", "parker-jotter-pen"],
  },
  {
    customerIndex: 7,
    productSlugs: ["lego-classic-bricks", "barbie-dreamhouse", "hot-wheels-track-set"],
  },
  {
    customerIndex: 9,
    productSlugs: ["dell-inspiron-15", "dyson-v15-detect", "garmin-forerunner-255"],
  },
  {
    customerIndex: 10,
    productSlugs: ["dumbbell-set-20kg", "yoga-mat-pro", "puma-training-tshirt"],
  },
  {
    customerIndex: 11,
    productSlugs: ["boat-airdopes-131", "oneplus-nord-ce-4", "kelloggs-corn-flakes"],
  },
];
